services:
  mysql-db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=root
    ports:
      - "32769:3306"
    restart: always

  match-result-service:
    build:
      context: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysql-db
